### ISSUE TITLE
LTT Webhook for #tech

### ISSUE THREAD

**Issue by n3bb** [CyberDiscovery/meta#364] opened 2020-06-09 11:07 UTC
Literally every single LTT video gets posted to #tech, so we might as well add a webhook and save Linucks the trouble of adding them by hand.

**Comment by Sh3llcod3** [comment] 2020-06-09 11:19
<img src="https://discordemoji.com/assets/emoji/9909_uwucat.png" style="height: 120px; width: 120px;" > #348

**Comment by RealJammy** [comment] 2020-06-09 12:15
Or maybe a channel just for webhooks that isnt social, so live overflow videos and other interesting topics can also go in there

**Comment by Sh3llcod3** [comment] 2020-06-09 13:15
Absolutely. :+1: for live overflow, definitely falls within my top tier content creators.

**Comment by thebeanogamer** [comment] 2020-06-22 09:42
Duplicate of #348

**Closed as completed by thebeanogamer** 2020-06-22 09:42 UTC
