### ISSUE TITLE
Tre wants a #tech

### ISSUE THREAD

**Issue by BoatiestBoat** [CyberDiscovery/meta#237] opened 2019-06-10 17:24 UTC
# Give Tre a tech, please

### *A description of the issue:*
Tre is sad he doesn't get a #tech and when Tre's sad I'm sad and that's bad

### *Proposed Solution:*
Give the man a #tech 

### *Additional Comments:*
Pretty please

**Comment by Trefonix** [comment] 2019-06-10 17:40
:this:

**Comment by thebeanogamer** [comment] 2019-06-10 18:15
Closed as duplicate of #233

**Closed as completed by thebeanogamer** 2019-06-10 18:15 UTC
