### ISSUE TITLE
Ana for root

### ISSUE THREAD

**Issue by NateKomodo** [CyberDiscovery/meta#201] opened 2019-05-12 20:12 UTC
Ana very good person and would bring good benefits and diversity to the root team

**Comment by lightspeedana** [comment] 2019-05-12 20:51
@NateKomodo You'll have to explain what benefits and what diversity I'd bring to the team, specifics are better for this kind of situation where there isn't really a majority in favour 😄

**Comment by lightspeedana** [comment] 2019-05-12 20:51
I don't really think I'd make a huge difference if I was brought into the role, but the decision is up to others and not me.

**Comment by SSAFuze** [comment] 2019-05-12 20:56
Well teamshortcut has thumbed up so lets consider the issue closed and accepted.

**Comment by ZomBMage** [comment] 2019-05-12 20:58
> Well teamshortcut has thumbed up so lets consider the issue closed and accepted.

That's not how democracy works, that's autocracy. The endorsement of the owner doesn't mean it should be instantly accepted without discussion within the root team

**Comment by lightspeedana** [comment] 2019-05-12 21:07
> Well teamshortcut has thumbed up so lets consider the issue closed and accepted.

Issues in meta tend to need to be approved by at least two members of the staff team, and since I'm directly involved here, it's best I don't vote on it. Therefore, only @teamshortcut saying something isn't yet good enough, and I think @thebeanogamer would have to approve this too in the first place, before a promotion is even remotely decided upon.

**Comment by NateKomodo** [comment] 2019-05-12 21:08
The main reason I believe ana should be root is that she feels a lot more connected to the community and is more of a people person then the current roots (99% of the server likes ana) and she would make the community more connected in a good way with the root then they currently are with shorty and bean man bureaucrat. She is also very reasonable in usage of power and influence.

**Comment by NateKomodo** [comment] 2019-05-12 21:09
I think I can reasonably say the majority of the server supports this

**Comment by ZomBMage** [comment] 2019-05-12 21:10
> I think I can reasonably say the majority of the server supports this

that's your opinion, let the people speak for themselves

**Comment by SSAFuze** [comment] 2019-05-12 21:11
Well i think the people would agree. But most people are unlikely to participate in this meta repo so perhaps members of the Discord server should be polled

**Comment by ZomBMage** [comment] 2019-05-12 21:12
> Well i think the people would agree. But most people are unlikely to participate in this meta repo so perhaps members of the Discord server should be polled

Congratulations, you realised the reason for #meta

**Comment by NicholasG04** [comment] 2019-05-12 23:27
@lightspeedana absolutely ridiculous comment to suggest that there is not a majority in favour.

**Comment by NicholasG04** [comment] 2019-05-12 23:29
I am finding comments by @ZomBMage to be appalling - how can there be any reasonable question of this going through? I am it full support of @NateKomodo

**Comment by ZomBMage** [comment] 2019-05-12 23:31
> I am finding comments by @ZomBMage to be appalling - how can there be any reasonable question of this going through? I am it full support of @NateKomodo

I'll have you know I'm in favour of Ana becoming root, I just think more democratic discussion should occur.

**Comment by NicholasG04** [comment] 2019-05-12 23:33
@ZomBMage need your comment be quite so agressive; I do however see that mine may have been taken unintentionally negatively too, for which I apologise. A vote would likely be ideal, yet I think this issue needs to be closed at a fast pace so that we can progress further in pushing Ana up the hierarchy to where she belongs.

**Comment by teamshortcut** [comment] 2019-05-13 10:47
More than open to this idea; if a PR is made, staff can discuss it and then it can go to a public vote in #meta.

**Comment by NateKomodo** [comment] 2019-05-14 07:27
@teamshortcut What am I supposed to PR

**Comment by teamshortcut** [comment] 2019-05-14 07:44
@NateKomodo add a line to [MISCELLANEOUS.md](https://github.com/CyberDiscovery/meta/blob/master/MISCELLANEOUS.md); catch-all for things that don't fit in the other files.

**Comment by lightspeedana** [comment] 2019-05-15 20:38
_Can I presume this is fairly dead now or not?_

**Comment by SSAFuze** [comment] 2019-05-15 20:41
@lightspeedana I believe the issue is now mostly irrelevant due to the ongoing issue #207

**Comment by NicholasG04** [comment] 2019-05-15 21:01
> 
> 
> _Can I presume this is fairly dead now or not?_

Not at all. I'm still quite willing to support this regardless of the outcome of #207. However, if it was decided that there'll be a process for gaining new sudos I guess it could change things. Regardless I still think you should get Root ASAP to be involved in the process

**Comment by teamshortcut** [comment] 2019-05-16 06:45
I would like to see this go to a PR, and given enough support if voted on in #meta, I see no reason why this couldn't happen before and in preparation of a wider change as described in Issue #207.

**Comment by teamshortcut** [comment] 2019-05-20 19:53
Resolved by #212

**Closed as completed by teamshortcut** 2019-05-20 19:53 UTC
