### ISSUE TITLE
Clarify punishment types and lengths

### ISSUE THREAD

**Issue by rak1507** [CyberDiscovery/meta#299] opened 2019-11-09 23:10 UTC
It should be a lot clearer to see what punishments are for what infringements, and what classes as an infringement in the first place.

### __**ISSUE**__
At the moment, the punishments seems very vague, with vague rules about what is or isn't allowed, specifically with regards to 'doxing', and with seemingly non-existent mod guidelines about what a suitable punishment is for various infringements.
Recently, as I'm sure everyone is aware, me and Rowan were both temporarily banned for a whole 14 days, for 'doxing' and 'harassment'.
Firstly, I think the mods need to seriously reconsider what constitutes as doxing. The images me and Rowan posted (that I also removed out of guilt a mere second after posting), were from youtube videos on a members channel that was linked directly to their discord account.
Personally, it is my opinion that if information is 2 clicks away from someone's discord account, posting said info does not constitute doxing in any form. It is also particularly frustrating when mods who aren't aware of the situation make rash and uninformed comments, as people look up to them, and in my opinion as a mod, commenting on a ban before you have the full picture is simply unacceptable and downright negligent.

Secondly, lets address the only real criticism of what me and Rowan did, the harassment.
It is obviously very difficult to decide what is a suitable punishment, as harassment is a very broad spectrum. However, what was said by me in particular was completely SFW, and absolutely pales in comparison to some of the things that have been directed towards members before. Granted, what Rowan said was definitely more offensive, but again, things a lot worse, or roughly on the same level as that have been said frequently before in a much more serious manner, but have only resulted in short mutes, and ultimately nothing much has come of it.
I definitely think the way I and others have acted towards new and less experienced members of the server has to change, as looking from an outsiders perspective it does seem a bit daunting, I've been there myself, but also we shouldn't give too much sympathy towards people who insist on demanding help, and want to be carried through the entire course from an early stage.

Fundamentally, I think the issues that I have tried to touch on in this issue penetrate much deeper than just mine and Rowan's ban, and it is a fundamental issue of extreme mod bias and no proper system for mods to determine appropriate punishments.

### __**PROPOSED SOLUTION**__

It is very hard for me to decide what I should write here, as realistically I don't think this issue will cause any change, especially considering the weight of the issues. Personally, I feel like this won't be fully fixed until several unnamed mods are demoted or at the very least change their downright extreme positions, or until someone who actually cares is appointed Sudo, or one of the Sudos who cares is appointed Root, if not preferably Owner.
One 'bandaid' fix I do propose though, is a **public**, **comprehensive**, and **community-approved** guideline for punishments, increasing clarity with regards to punishments 100-fold. It has become clear now that mods refuse to justify their decisions, and that in their opinion, we shouldn't even be questioning them in the first place. I am unwilling to accept this until we have something that clearly sets out reasoning behind punishments, and I believe such a guideline would act as a **temporary** fix, until some serious re-evaluation took place behind the scenes.
I would also of course like to see Rowan and I's cases re-evaluated, and I would propose either an immediate unban, or a reduction of the ban length, in accordance with what several respected members of the community feel is fair, and in accordance with past punishments.

Please feel free to add your opinions, I hope this post at the very least causes some discussion.

**Comment by ThisIs0xBC** [comment] 2019-11-09 23:30
I agree with this, there have been many occasions where certain mods that I won't name seem to just make up rules and justify them with "I'm sudo so you do what I say". It is extremely annoying to see said certain moderators act so out of line with the rest of the team, they're like a loose cannon. There are also extremely bad double standards due to there being no guidelines set in stone for the moderators, sometimes a moderator will punish one person for something much less severe than something someone else has done, or punish two people differently for the same offence and severity. May it be due to the mood they're in currently, or whether they like/dislike that person, their decisions should **not** be affected by this, yet they still seem to be.

**Comment by teamshortcut** [comment] 2019-11-09 23:30
You want a full on judiciary system for a volunteer run Discord server... the mods spent a large part of the evening in question justifying their decisions, as they do all the time, people just don't always like the answer. Instead of moaning because you believe you're entitled to a 100% consistent system (you know real-life actual courts don't acheive that right?), you could just wait two weeks and move on with your life. Your proposed solution largely boils down to "I don't like the mods and want things to conform to be convenient for me specifically".

**Comment by R0w4nS** [comment] 2019-11-09 23:38
I'm going to comment on this, as this issue includes me specifically. I fully accept that what I did was wrong, and that I shouldn't be unbanned. However, I do think that more clarification and consistency on punishments would be a positive change - a change that the mods could benefit from too.

**Comment by ThisIs0xBC** [comment] 2019-11-09 23:39
@teamshortcut 

> Your proposed solution largely boils down to "I don't like the mods and want things to conform to be convenient for me specifically".

This is bollocks. His proposed solution would actually save countless hours for the moderators as they wouldn't have to spend so long arguing over someones punishment, as it would most likely be in the guidelines. It might also lower the amount of incidents, as more people know what **is** and **isn't** acceptable.

**Comment by teamshortcut** [comment] 2019-11-09 23:40
> Personally, I feel like this won't be fully fixed until several unnamed mods are demoted or at the very least change their downright extreme positions, or until someone who actually cares is appointed Sudo, or one of the Sudos who cares is appointed Root, if not preferably Owner.

"bollocks".

**Comment by ThisIs0xBC** [comment] 2019-11-09 23:43
So he holds an opinion shared by a multitude of other people? Nothing wrong with that, if he and many others see that certain moderators act out of line, then there is clearly a problem.

**Comment by Little-Green-Guy** [comment] 2019-11-09 23:45
I think you're missing the point here shortcut. We do not want a full judiciary system. That wouldn't be appropriate and probably would work.

What is being proposed is for us to help create a system which will improve the server and the moderators ability to achieve consistency, which although complete consistency may not be possible, more consistency is a goal.

And yes, this is a volunteer run server, but the volunteers took up responsibility to run this server and to try and run it well. While I will not comment on this exact example, the meta issue is not setting out to resolve this isolated case but instead try to improve the system and help with the moderation of the server.

**Comment by Bottersnike** [comment] 2019-11-09 23:56
> One 'bandaid' fix I do propose though, is a public, comprehensive, and community-approved guideline for punishments

This is not only a pipe dream, but it would be horribly unfair on the (human, mind you) mods to expect them to follow a "comprehensive guideline" for punishments. Either it's so comprehensive that it's impossible for a human, and so it gets merged into the bot instead, or it's not "comprehensive enough" because the mods are still allowed to, shock horror, decide things, and people complain about their decisions.

**Comment by actuallynotdave** [comment] 2019-11-10 00:01
Look, I don't want to get involved in CD politics anymore but I feel like this needs to be said. Shortcut, you're not an admin anymore. Please stop being a backseat admin, you're making everyone's life worse, it doesn't help the admins because you still have a fair bit of perceived authority so it makes it more difficult for them when you're wrong, it doesn't help the community because they end up not being able to actually have meaningful discussions with each other and instead have to "debate" you, and it's just a waste of your time. You're intentionally misinterpreting what is being said to protect your friends. I get that, it's human instinct however if you really cared about the community, you'd let the issues be raised and you'd let your friends on the staff team get on with their job uninterrupted.

**Comment by Little-Green-Guy** [comment] 2019-11-10 00:03
I think a public set of guidelines would still be beneficial.

Although mod actions are often made very quickly due to the nature of situations so guidelines would need some flexibility a public set of guidelines that mods can bear in mind when they take actions would allow for more consistency and the ability to go back, review and amend decisions later would help this.

**Comment by ZomBMage** [comment] 2019-11-10 00:04
![image](https://user-images.githubusercontent.com/29120255/68536621-70ea7480-034d-11ea-8aff-fb70fde54e67.png)
Additionally, I hardly see how this is productive. I may not be in the community at the moment but I still care about it thriving, and it's clear to me that Shortcut has not actually read what Rak posted originally, but what he wanted to instead. While Rak's solution may not be the most practical, I appreciate that he's willing to step out and make the effort to actually *fucking suggest* something to make the server a better place, and doesn't need people like Shortcut rejecting an idea that quite frankly he chose not to read, and instead offer nothing to the contrary.
Cute how he sticks up for his friends, regardless.

**Comment by actuallynotdave** [comment] 2019-11-10 00:07
Also totally unrelated but can you not change your verification settings to stop me responding, I own a mail server ffs.

**Comment by teamshortcut** [comment] 2019-11-10 09:14
I didn't realise ex-admins were barred from having and expressing their opinions, just like any other server member can; evidently my mistake.

**Comment by Little-Green-Guy** [comment] 2019-11-10 11:31
I think the problem here is that you were expressing an opinion that didn't line up with the actual issue and was mostly irrelevant. You were attacking members for making suggestions to try and improve the server. Yes, rak being banned was probably the trigger for the issue, but it certainly wasn't what the issue boiled down to.

Also I think rejigging the staff would be beneficial. We have one active root who cares about the server and seems to be under a lot of stress because of it which isn't great.

**Comment by actuallynotdave** [comment] 2019-11-10 12:44
I never said you couldn't express an opinion. The issue is with the way you do it, you're trying to deliver a definitive no when that's simply not for you to do anymore, instead of just blindly shooting down suggestions, try actually suggesting an alternative. The server needs some serious change, in part because of the precedent your caliber of response has set, you're no longer an admin so it's no longer your responsibility but you're still trying to stop change. You're not attempting to even provide a reason that the suggestion is invalid, you just resort to ridiculing the issue straight away, all that does is make you look bad. If a different person opened the exact same issue, you would have had a very different response. It's been clear for a long time that the punishment system needs reworking, so what's your suggestion?

**Comment by Trefonix** [comment] 2019-11-10 13:38
Hi,

I understand your concern, and that it's frustrating that there is very little clarification on what situation warrants which punishment. The issue is that, with every case being vastly different in terms of context leading up to the event and the severity of the offence, it would be both unrealistic for us to anticipate everything and unfair to apply a fixed punishment for every variation. In addition, as far as mutes are concerned, the emphasis is on dealing with the problem as swiftly as possible, which means that we often only get a few seconds to evaluate and judge a suitable solution. It's unideal that there's variation between moderators, but the tradeoff is we are dynamic and able to quickly react to a large number of situations. 

Your points are valid, however, we try to balance fair discussion with each moderator having room for discretion. In my opinion, the improvement can be made to documenting each case and providing a short, clear justification which doesn't seem unreasonable to me.

Regards,

Trefonix

*This post and any other posts I make are reflective of my personal opinions and do not necessarily reflect the stance of the staff team as a whole or any other individuals on the staff team*

**Comment by Little-Green-Guy** [comment] 2019-11-10 14:27
I understand that issues need to be acted upon quickly so it is difficult to judge and different moderators will act differently, but I think that a rough set of guidelines would still help with this as ideally they would be short enough that you would be able to remember them and not have to reference them.

I also fully support documenting cases with brief justification as I mentioned in #283

**Comment by rak1507** [comment] 2019-11-30 16:17
Seems like this will never happen.

**Comment by NicholasG04** [comment] 2019-11-30 16:18
rak i miss u already

**Comment by rak1507** [comment] 2019-11-30 16:18
Thanks

**Comment by Little-Green-Guy** [comment] 2019-11-30 16:19
can this be re-opened?
it's still a legit issue that needs solving.

**Comment by RealJammy** [comment] 2019-11-30 16:23
Yep we should re-open this

**Comment by rak1507** [comment] 2019-11-30 16:25
It is a legit issue, but after no replies for 20 days I'm sceptical anything will change.

**Comment by Little-Green-Guy** [comment] 2019-11-30 16:25
yes but it should remain open to show it is still an issue

**Comment by rak1507** [comment] 2019-11-30 16:29
Ok, I've reopened this because it is still an issue.

**Comment by thebeanogamer** [comment] 2019-11-30 16:42
This issue was temporarily closed because GitHub banning is kinda a mess.

**Comment by ThisIs0xBC** [comment] 2020-01-08 23:00
Opened on November 9th, 25 comments over a span of 3 weeks, with most commemters agreeing and very few disagreeing, yet nothing came from it. #meta in a nutshell.

**Comment by Little-Green-Guy** [comment] 2020-01-13 11:08
This issue is also soon to be resolved by #315

**Comment by lightspeedana** [comment] 2020-01-13 14:34
Right closing time, since #315 covered this.

**Closed as completed by lightspeedana** 2020-01-13 14:34 UTC
