### ISSUE TITLE
Allowance of Really Awesome CTF in the #friends-of-cd channel

### ISSUE THREAD

**Issue by Bentechy66** [CyberDiscovery/meta#236] opened 2019-06-08 17:30 UTC
# Allowance of Really Awesome CTF in the #friends-of-cd channel

### *A description of the issue:*
For whatever reason, it appears that, even after my sustained attempts, the Really Awesome CTF is not yet in the friends of cd channel while many other "CTF"s of lesser quality (
"challenges, "PizzaCTF") are allowed. I see no reason and have not been given a reason it should not be in there.

### *Proposed Solution:*
Add https://discord.gg/CzqnHde to friends of cd.

### *Additional Comments:*
The fact that there isn't clear criteria to get into the affiliate channel doesn't help this matter. This is somewhat unrelated and perhaps calls for another issue entirely.

**Comment by NicholasG04** [comment] 2019-06-08 17:32
I completely agree that this should be added with immediate effect. It has happened because of the hard work of talented and committed members of the community such as yourself and deserves to be honoured as such based on that fact alone.

**Comment by ZomBMage** [comment] 2019-06-08 17:35
PizzaCTF currently may as well be dead. As for RACTF, the past discussions with CD staff about affiliation descended into personal attacks between members of staff on both ends - far from ideal - however I feel these discussions could have been handled much differently and a much different outcome could have been reached. As both prospective hoster of RACTF as well as an original member of staff, any of the root team are fully welcome to discuss this matter with me if they wish. I personally see no reason against affiliation.

**Comment by NicholasG04** [comment] 2019-06-08 17:37
In fact I think denying affiliation would simply be, as you stated, a personal attack that is entirely unreasonable.

**Comment by ZomBMage** [comment] 2019-06-08 17:38
I'd like to make it clear I have no intentions on naming names about who was involved in this, but I wasn't there to participate at the time - only to witness the fallout later in the evenings

**Comment by Bentechy66** [comment] 2019-06-08 17:40
I will agree that the way it was handled was non-ideal to say the least, namely that one member from each side (again, I won't name names) was personally attacking the member from the other party. This isn't how I would have liked it to go and hope we can put this behind us in the name of more civilised discussion.

**Comment by teamshortcut** [comment] 2019-06-08 18:31
At this point, I feel like I've answered this so many times I've lost track of what I have and haven't said; but here we go again I suppose. To reiterate comments I've made elsewhere, or to add to them if I haven't yet fully explained these:

Servers are added to #friends-of-cd if they are servers that we feel is a place in keeping with our own community, if they are relevant and helpful to our members, and if there is a relationship between our servers and theirs. RACTF meets the second, but so does any CTF platform in existence. (#resources is better suited to this, which I have said in the past) The difference here is that, this particular CTF is partially run by members of our community, but our policy (and this is far from the only case of applying this) is that this isn't enough to be put in #friends-of-cd. Our members are multi-talented, and if we put everything they did into the channel, it would quickly become clogged. The fact it is partly run by a banned member of ours does not help (we're hardly going to jump to endorse it), and contributes to the larger point raised already that the relationship between our staff and yours has been far from cordial. (I'll fully admit to have been part of the cause of that, but I was hardly unprovoked)

To address the examples you cited, PizzaCTF is, to the best of my knowledge, dead as a doornail (and no longer in the channel anyway), and I don't honestly know the reasons the `challenges` server was added, as it was before my time as admin. (you could argue it serves a more unique purpose I guess, but that's fairly subjective) The channel itself is largely a relic of previous administration that we haven't gotten around to overhauling (or honestly retiring) just yet. However, in the meantime, an online CTF run by members who are hardly cultivating a professional relationship is not something we want to be directly affiliated with. By all means post it in #resources, #challenges or elsewhere - if the Discord server is so integral, I can add a whitelist to the bot, pin the message, or am open to other suggestions to compromise - but it's not something we want to have a direct partnership with.

**Comment by NateKomodo** [comment] 2019-06-08 18:42
Do it or riot

**Comment by teamshortcut** [comment] 2019-06-08 18:42
Riot and get muted.

See look, I can play this game too.

**Comment by NicholasG04** [comment] 2019-06-08 18:42
May I ask for a definition of 'we' and how you are able to represent their opinion; 'we' certainly doesn't represent the community's opinion I think...

**Comment by NateKomodo** [comment] 2019-06-08 18:43
@teamshortcut that’s suppression of freedom of expression ima have to arrest you now

**Comment by teamshortcut** [comment] 2019-06-08 18:44
@NicholasG04 `we` was referring to the staff team.

**Comment by NicholasG04** [comment] 2019-06-08 18:44
Having thought about it I think this brings onto another topic of discussion which is the role of admins.... are they to act as dictators harshly controlling the population or instead to be the representation of the people that do in fact give them their positions by being members....?

**Comment by NicholasG04** [comment] 2019-06-08 18:45
> 
> 
> @NicholasG04 `we` was referring to the staff team.

OK, and you have the right to represent all their opinions and they are all in agreement with your comments? Thanks.

**Comment by ZomBMage** [comment] 2019-06-08 18:45
I'd like to take a moment to ask @NicholasG04 to leave this discussion to the admins behind RACTF.

That aside, Both myself and @Bentechy66 have both offered with open arms to the staff team of CD for a more civilised discussion (just the two of us and whoever you'd like to include)

**Comment by NicholasG04** [comment] 2019-06-08 18:45
> 
> 
> I'd like to take a moment to ask @NicholasG04 to leave this discussion to the admins behind RACTF.
> 
> That aside, Both myself and @Bentechy66 have both offered with open arms to the staff team of CD for a more civilised discussion (just the two of us and whoever you'd like to include)

Happy to do so. Have a great day.

**Comment by teamshortcut** [comment] 2019-06-08 18:46
> Having thought about it I think this brings onto another topic of discussion which is the role of admins.... are they to act as dictators harshly controlling the population or instead to be the representation of the people that do in fact give them their positions by being members....?

@NicholasG04 That is a topic for a separate issue, but I will point out we are discussing a Discord server, not a government. And yes, staff who were online at the time were consulted before responding, so yes and yes in answer to your question.

**Comment by NicholasG04** [comment] 2019-06-08 18:47
> 
> 
> > Having thought about it I think this brings onto another topic of discussion which is the role of admins.... are they to act as dictators harshly controlling the population or instead to be the representation of the people that do in fact give them their positions by being members....?
> 
> @NicholasG04 That is a topic for a separate issue, but I will point out we are discussing a Discord server, not a government. And yes, staff who were online at the time were consulted before responding, so yes and yes in answer to your question.

Many thanks for your response :))

**Comment by ZomBMage** [comment] 2019-06-08 18:50
> Servers are added to #friends-of-cd if they are servers that we feel is a place in keeping with our own community, if they are relevant and helpful to our members, and if there is a relationship between our servers and theirs. RACTF meets the second

I'd argue the third point also is met as the entire development of the program has been undertaken solely by members of the CD server. While yes, we do have a banned user on the team and part of our admins, and that certainly didn't help the negotiation in the slightest, we have reached out to try to amend this and come to a satisfactory closure.

> However, in the meantime, an online CTF run by members who are hardly cultivating a professional relationship is not something we want to be directly affiliated with.

Please don't tar us all with the same brush. I've addressed this above!

> but it's not something we want to have a direct partnership with.

Please, consider this an open invitation to talk to myself and @Bentechy66 about any issues you may want to address in more depth or privacy than would otherwise be suitable for a github issues thread.

**Comment by Bentechy66** [comment] 2019-06-08 18:51
I feel the issue is moving away from the title - however your 3 criteria are something we never got given in the 2+ hours of discussion, so that's a start I suppose. Personally, I believe the server fullfills all 3 criteria - in what way is a community-made capture the flag not "in-line with your own community"? You literally run a community about infosec? Furthermore, I believe there is a relationship between our server and yours - the fact that it was made by community members should be enough. Your point about Dave being involved with the server is completely invalid and I do not see how that relates in any way to the discussion. As @ZomBMage has said, please, feel free to privately talk to us at any point.

**Comment by teamshortcut** [comment] 2019-06-08 19:07
@ZomBMage I understand that it's been developed largely by community members, but as I said above that isn't sufficient reason on its own. And while I'll happily acknowledge your responses have been more professional than some others, last I checked I was being asked for a platform-wide parternship, not just your portion of it 😉 

@Bentechy66 I specifically said the fact that it is a CTF is relevant, but that it isn't something we want to be partnered with for the reasons above. Whether or not you think that `it was made by community members should be enough` is somewhat irrelevant, as we have always (since I started as admin at any rate) said that isn't sufficient reason. I also don't personally see what's "invalid" that we are not immediately rushing to endorse projects run by banned members, but as claiming something is or is not valid doesn't really affect anything, feel free to arbitrarily mark other points from the response you asked for as legitimate or otherwise.

I'm not entirely sure what I would need to privately message either of you about, but if you preferred to move this into DMs you know where to find me.

**Comment by ZomBMage** [comment] 2019-06-08 19:10
I'm not sure what you mean by "platform-wide", could you elaborate a little, please?

> I'm not entirely sure what I would need to privately message either of you about, but if you preferred to move this into DMs you know where to find me.

We've both invited you talk to us in depth about the whole consideration of affiliation, without intervention from the less civil members of the admin team of RACTF so we can talk things through professionally.

Also, as a response to your comment above about not being sufficient enough for #friends-of-cd, but we could suggest alternatives, perhaps an announcement might suffice when we finally launch the actual CTF?

**Comment by teamshortcut** [comment] 2019-06-08 19:14
Poorly phrased comment that qualified as a joke in my tired, revision drained brain; I meant that I was talking to your entire team, for your entire project, not just to you individually, but that wasn't particularly clear, sorry about that.

If you have additional questions that you'd rather not discuss here, I'm happy to answer them in DMs; I don't personally have anything else I feel needs saying, though I'll let you know if any come to mind.

As I said above, happy to discuss alternative compromises, I'd said to @Bentechy66 that promoting the CTF in #resources or #challenges would be fine, and as I said above I'm happy to whitelist the Discord invite if it's integral to the platform, and/or pin the message in #resources/#challenges to prevent it getting lost.

**Comment by Bentechy66** [comment] 2019-06-08 19:18
>  I meant that I was talking [about] your entire team

As project founder, I speak here representing the team and I believe that there is still no reason we should not be affiliated with the server. I've discussed how I feel that our server hits the 3 requirements and stand by that, however an alternate solution would be an announcement when we launch the CTF?

**Comment by teamshortcut** [comment] 2019-06-08 19:22
And I, as server owner and representative of our staff team, believe that there is sufficient reason not to be affiliated with your programme, which I have outlined above, while specifically addressing how your server does not meet the criteria I set out above. Given that only one of us is able to action your request, my apologies if you disagree but I have (on so, so many occasions) made the response quite clear. I would have to check with the staff team about an announcement (by which I presume you mean a message in the #announcements channel), but my inclination would be that anybody who would want to take part would see it in #challenges, or failing that #resources, and an announcement is unnecessary and clogs up the channel.

**Comment by ZomBMage** [comment] 2019-06-08 19:27
> and an announcement is unnecessary and clogs up the channel

we've had minecraft servers in there before

**Comment by teamshortcut** [comment] 2019-06-08 19:28
This is true. We've not got a terrible streak of _actually relevant announcements_ right now, but true nonetheless.

**Comment by Bottersnike** [comment] 2019-06-08 19:37
I've been trying to avoid posting anything because it never goes well, but I just wanted to mention that
> We've not got a terrible streak

appears to go back like a year or so, with things ranging from Bax's ML course, MC servers, twitter posts, bingo games, IRL voting things, IRL exams, that mass of elite stuff, a random rainbow flag, etc.

**Comment by ZomBMage** [comment] 2019-06-08 19:38
What's wrong with my ML course!?

**Comment by teamshortcut** [comment] 2019-06-08 19:39
Exact length and quality of the streak is debatable, and somewhat irrelevant, but I do take your point.

**Comment by Sh3llcod3** [comment] 2019-06-08 19:40
Guys,

I'm no genius, but the man himself has spoken and unless one of you have a very good reason, it probably wouldn't be appropriate to keep nagging at it.

With that said, this is my response:

![Time_To_Stop](https://user-images.githubusercontent.com/28938427/59151574-64c05b00-8a2d-11e9-98b0-d5d6f12a7a32.png)

**Comment by phantasml** [comment] 2019-06-09 14:16
:wave: 
While I'm not affiliated with ra-ctf outside of being a participant, I still agree it should be put in #friends-of-cd. I don't speak for their administration, however I think @Bentechy66 may be happy with the invite being whitelisted and posted in #resources and #challenges.
An announcement would, I'm sure, be highly appreciated. The CTF is made by the community, for the community, and other things that follow that rule have made it into #announcements before, such as the previously mentioned Minecraft server. It also is closely linked to the server - as it's a ctf. The CTF may also allow the community to feel more community-like (not quite sure how to word that), similar to the effects of the Minecraft server for a little while. Things like this allow the community to thrive more, which benefits everyone.

Edit: I don't know if this counts as necroposting or not, as I'm unsure whether the issue is over or not. Apologies in advance.

**Comment by teamshortcut** [comment] 2019-06-22 15:47
Closing as the issue has since been resolved and a compromise was reached.

**Closed as completed by teamshortcut** 2019-06-22 15:47 UTC
